### PR TITLE
Strictly typed functions and unicode to wstring conversions

### PR DESCRIPTION
**Pull request by ziab**
* C++ functions bound to lua expect strict types and arguments count, otherwise cause `luaL_error`, example:

`bad argument #-1 to 'typeSafeFunc' (string expected, got number)`
`expected parameters count: 3`
* Lua should be compiled as C++ otherwise it will *long jump* instead of throwing an exception, which may cause memory leaks and undefined behavior
* Lua unicode strings are converted to wstrings when C++ function expects wstring. This might be desired when code is written for Win32
* C++ functions can `throw LuaNil()` excpetion and Lua code will get `nil` return value, like this:

```
int cpp_func_returning_int()
{
...
   if (!some_condition)
      throw LuaNil();

   return value;
}
```

* Added new unit test
* Added specialization for raw Lua C functions with `int(lua_State*)` signature

Note, the code is raw and tested only with MSVC
Not sure if these features are really needed in master branch of luacppinterface. There could be 2 different registrations of functions, like:
```
Lua.CreateFunction<int(int)>(func);
Lua.CreateStrictFunction<int(int)>(strict_func);
```

### CODE REVIEW

**Comment by davidsiaw** [comment]
Hey, thanks for the pull request. Travis does not seem so happy about it though...

**Comment by ziab** [comment]
Hi, I've fixed type being used as a value issue. Windows build now fails with linkage errors caused by name mangling issue, MSVC project settings should be updated, i'll do that later this week. GCC build seems to fail because UNREFERENCED_PARAMETR macro is not defined, it's a macro that is defined in Windows headers, well it's fixable.

**Comment by davidsiaw** [comment]
Apparently the build still isn't fixed. looks like pip --use-mirrors is dying

**Comment by davidsiaw** [comment]
if you try pull the main repo and push to yours you should get --use-mirrors fix in this pull request

**Comment by davidsiaw** [comment]
well, looks like a different error now.

**Comment by ziab** [comment]
Yup, looking into it. Just out of curiosity, can I submit a change directly to Travis from my local machine, without committing a change into the repository? 

The thing is that I tested this with MSVC, but GCC and Clang throw different errors, I can test it locally with Cygwin + GCC though, just need to install it.

**Comment by davidsiaw** [comment]
Commit to travis? Not that I know of. I know what you mean though

**Comment by ziab** [comment]
Yeah, in the company where I'm working we call it "virtual build".  Looks like the last issue is: luaerror.h: error: extra qualification . Gonna fix it tomorrow.

**Comment by davidsiaw** [comment]
This set of changes is getting quite large. Can you please move it into a branch on your repository so I can pull the topic branch and we can work on it together? I have win32, linux and mac machines here so I can test everything locally and maintain the non-win32 stuff easier

**Comment by ziab** [comment]
Sure, the changes are in my fork: https://github.com/ziab/luacppinterface
I'll also fix the issues you pointed above.
Closing the pull request.

**Pull request closed without merging**
